spring:
  datasource:
    url: jdbc:h2:jdbc:h2:tcp://localhost/~/test;auto_server=true
    username: sa
    password:
    driver-class-name: org.h2.Driver

quartz:
  enabled: true

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yml

job:
  example:
    repeat:
      frequency: 5000
    cron:
      expression: 0/10 * * * * ?